apps/mascota/urls.py
from django.conf.urls import url
from apps.mascota.views import listadousuario, index, mascota_delete,  mascota_list, mascota_view, mascota_edit
from apps.mascota.views import MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar$',login_required(MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    url(r'^listado', listadousuario, name='listado'),
]

miproyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView , PasswordResetCompleteView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include(('apps.mascota.urls', 'mascota'), namespace="mascota")),
    url(r'^adopcion/', include(('apps.adopcion.urls', 'adopcion'), namespace="adopcion")),
    url(r'^usuario/', include(('apps.usuario.urls', 'usuario'), namespace="usuario")),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^accounts/login/', LoginView.as_view(template_name='index.html'), name='login'),
    url(r'^reset/password_reset', PasswordResetView.as_view(), {'template_name': 'registration/pasword_reset_form.html', 
    'email_template': 'resgistration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done', PasswordResetDoneView.as_view(), {'template_name': 'registration/password_reset_done.html'},  name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(), {'template_name': 'registration/pasword_reset_confirm.html'},   name='password_reset_confirm'),
    url(r'^reset/done', PasswordResetCompleteView.as_view(), {'template_name': 'registration/pasword_reset_complete.html'},  name='password_reset_complete'),
]

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

# Create your models here.

class Vacuna(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad = models.IntegerField()
    fecha_rescate = models.DateField()  
    persona = models.ForeignKey(Persona, null=True, blank = True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank= True)

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]

        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad':'Edad Aproximada',
            'fecha_rescate': 'Fecha de rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

apps/mascota/views.py
from dataclasses import fields
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import redirect, render
from apps import mascota
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
from django.core import serializers
from django.contrib.auth.models import User

# Create your views here. 



def listadousuario(request):
    lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name'])
    return HttpResponse(lista, content_type='application/json')



def index(request):
    return render(request, 'mascota/index.html')



def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:index')
    else:
        form = MascotaForm()
    return render(request, 'mascota/mascota_form.html', {'form': form})



def mascota_list(request):
    qset_mascota = Mascota.objects.all().order_by('id')
    contexto = {'mascotas': qset_mascota}
    return render(request, 'mascota/mascota_list.html', contexto)



def mascota_edit(request , id_mascota):
    qset_mascota = Mascota.objects.get(id = id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=qset_mascota)
    else:
        form = MascotaForm(request.POST,  instance=qset_mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_form.html',  {'form': form})



def mascota_delete(request, id_mascota):
    qset_mascota = Mascota.objects.get(id= id_mascota)
    if request.method == 'POST':
        qset_mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})




## Vistas como clase (ListView)
class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'


class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')


class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}


{% block title%}
    App Mascota
{% endblock %}

{% block header%}
{% include 'base/header.html' %}
{% endblock %}


{% block content %}
    Soy el contenido de mascota
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <h3>¿Desea eliminar la mascota {{ object.nombre }}?</h3>
    <button class="btn btn-danger" type="submit">Eliminar</button>
    <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Guardar</button>
</form>

{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{%  block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha</td>
            <td>Adoptante</td>
            <td>Acciones</td>
        </tr>
    </thead>

    <tbody>
    {% if object_list %}
        {% for mascota in object_list%}    
        <tr>
            <td>{{ mascota.id }}</td>
            <td>{{ mascota.nombre }}</td>
            <td>{{ mascota.sexo }}</td>
            <td>{{ mascota.edad }}</td>
            <td>{{ mascota.fecha_rescate }}</td>
            <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellido }}</td>
            <td>
                <a class="btn btn-primary" href="{%  url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                <a class="btn btn-danger" href="{%  url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>

            </td>
        </tr>
        {%  endfor %}

    {% else %}
        <h1>No hay registros de mascotas.</h1>
    {% endif %}
    </tbody>

</table>


{% endblock %}

templates/mascota/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products</title>
</head>
<body>
    <h2>Your parameter value is : {{id}}</h2>
</body>
</html>